### ISSUE TITLE
Smithing is not working

### ISSUE THREAD

**Issue by solohex** [Wildlander-mod/Support#10]
Hi there for some odd reason the smithing skill tree is not working, here is what i'm experiencing

1. 1st perk isn't unlockable unless you pick it at the character creation.
2. If picked at creation it only allows 1st perk and the one above it no other perks can be gained for some reason.
I don't know what is going on with it at the moment any help is very much appreciated, have a good day.

**Comment by Mieekaserra** [comment]
Smithing tree is working as intended. You need books in your inventory to unlock perks. The wiki has a page with the locations of the books.

**Comment by solohex** [comment]
ok thank you
