### ISSUE TITLE
FAQ contradicts itself on Anniversary Edition

### ISSUE THREAD

**Issue by ville-v** [Wildlander-mod/Support#11]
FAQ contradicts itself on Anniversary Edition:

https://github.com/Wildlander-mod/Support/wiki/FAQ#what-version-of-special-edition-is-needed
https://github.com/Wildlander-mod/Support/wiki/FAQ#do-i-need-to-buy-the-anniversary-edition-dlc
https://github.com/Wildlander-mod/Support/wiki/FAQ#getting-a-download-failed-on-original-skyrim-files

On Steam, "Skyrim Anniversary Edition" is a bundle that includes "Skyrim Anniversary Upgrade":

![anniversary edition](https://user-images.githubusercontent.com/22340294/170852146-0e0c44c5-0862-4721-8311-d0d76c05c320.png)

This is not required. Instead, only "Skyrim Special Edition" is required. The newest update of the Special Edition is called "Skyrim Anniversary Edition":

![anniversary edition 2](https://user-images.githubusercontent.com/22340294/170852150-17c49ed7-7581-4236-bed1-f2ae62ebb886.png)

The FAQ should clearly say that only the "Skyrim Special Edition" is required and "Anniversary Edition" means two different things. This might be obvious to someone who owns the game but it isn't for someone who is buying Skyrim to play Wildlander. Perhaps all three answers that I linked should be clarified.

**Comment by Mieekaserra** [comment]
Clarifications made.
