### ISSUE TITLE
Typos and improvements for Intro to Wildlander

### ISSUE THREAD

**Issue by silicon-ghost** [Wildlander-mod/Support#12]
**Which page**
https://github.com/Wildlander-mod/Support/wiki/An-Introduction-to-wildlander

**Description of issue**
Some suggestions for typos/wording.
Old text:
You also no longer have passive health regeneration, so having some form of healing is required - weather than be via Potions, polutices or spells.
New text:
You also no longer have passive health regeneration, so having some form of healing is required - whether that be via Potions, poultices or spells.
**Screenshot to help me find it**
![image](https://user-images.githubusercontent.com/566490/171761864-263bd7b1-c944-4112-91c7-bb2aae5c7bac.png)

**Description of issue**
Some suggestions for typos/wording.
Old text:
bulleted list of armor choices
New text:
a table is easier to read.  I'm not sure of best way to describe warmth/wet protection options.  Does it make sense to split into 2 columns?  Make sure to leave a blank line before table so Github will render the table properly.

| Type    | Protection | Movement | Spell Penalty | Warmth/Wet Protection |
| ----    | :--------: | :------: | :-----------: | :-------------------: |
| Cloth   | None       | Fast     | Low           | Typically little Warmth/Wet |
| Evasion | Low        | Medium   | Medium        | Typically best Warmth/Wet |
| Heavy   | High       | Slow     | High          | Typically worst Warmth unless fur-lined |

**Screenshot to help me find it**
![image](https://user-images.githubusercontent.com/566490/171762951-f88a0189-2f45-4920-b1f0-b97ca8d340b2.png)

Patreon: Matthew Zaleski
Discord: NeuroticGamer#8664

**Comment by Mieekaserra** [comment]
Changes made - Thank you!
