### ISSUE TITLE
Holding block button increases stamina regen

### ISSUE THREAD

**Issue by ShdwKnght** [Wildlander-mod/Support#15]
I have the default install of Wildlander unmodified. I am on a Breton character with Mage stone. Wearing a full iron heavy armor set and no buffs except for one applecabbage stew. My stamina regens maybe two or three times faster when I am holding up block out of combat. I did not test in combat. I believe this is doing the exact opposite of what the wiki page about holding block says. > "Holding your shield or weapon up to block a attack will inflict a stamina drain."

**Comment by Mieekaserra** [comment]
not the place to raise bug report

Please answer all questions with as much detail as you can give us

https://forms.gle/2iDbY5Hb6L32oDRG6
