### ISSUE TITLE
Dragons do not provide any loot

### ISSUE THREAD

**Issue by qDshun** [Wildlander-mod/Support#16]
After killing a dragon, most of the times it has no loot inside. Sometimes (like 2 times out of 6 i got that menu that allows to skin it, but most of the times they're just like containers with nothing and you can not skin them). I was not doing any changes to modpack, so cant figure why its behaving that way

**Comment by Mieekaserra** [comment]
That would be why its on the known issues.

Dragons added by the dawnguard expansion have no lootable. (They can appear at any spawn spot)

**Comment by qDshun** [comment]
Thanks! I solved it by Taxonomy abilty marking it as a dragon
