### ISSUE TITLE
Game crashes after Quickload.

### ISSUE THREAD

**Issue by FailAlot** [Wildlander-mod/Support#17]
In the last 2 days the game crashes every time I want to quickload. I can start and play the game, however if I die or want to start from previous save file, I always crash. 
In the crash log there is always the same code/number: 
"Unhandled native exception occurred at 0x7FF6B8DCDC5B (SkyrimSE.exe+12DC5B) on thread 14776!"
Here is the crash log. Thanks in advance.

[Crash_2022_8_4_13-4-56.txt](https://github.com/Wildlander-mod/Support/files/9259214/Crash_2022_8_4_13-4-56.txt)

**Comment by Mieekaserra** [comment]
https://github.com/Wildlander-mod/Support/wiki/Crash-Help#save-corruption-skyrimseexe12dc5b

**Comment by FailAlot** [comment]
Thanks for your help. Sorry to bother you. Do I need to find that cloak and remove it? I might be too stupid to find the solution for it.

**Comment by Mieekaserra** [comment]
It has nothing to do with a cloak. you are reading the wrong section!

This crash means your save has corrupted - there is no fix.  Only solution is to roll back saves until you find one which works correctly.

Recommendations to reduce chance of reoccurrence

Dont same more than one a minute
Never save in combat
Avoid saving right after entering a building/cave/dungeon.
If you have re enabled autosaves - turn them off.

**Comment by FailAlot** [comment]
Oh noo. That is sad. Thank you for your help
