### ISSUE TITLE
RP Class Guide - Knight of the Iron (Zenithar's Champion)

### ISSUE THREAD

**Issue by AchillesMV** [Wildlander-mod/Support#19]
**Where should your new page go**
class guides
**Summarise the contents of your page**
to create a rp class guide

**Page Contents**
https://docs.google.com/document/d/14j6hVWBxCv-qW_6Hz2C7FPxuQi0KxY5wDtmuEGdGR7Q/edit?usp=sharing

**Comment by AchillesMV** [comment]
Two roleplaying scenarios were added to the doc.

**Comment by Mieekaserra** [comment]
Page added and updated.
