### ISSUE TITLE
Crispy's Guide to Owning and Using Horses

### ISSUE THREAD

**Issue by JustPlainOldCrispy** [Wildlander-mod/Support#22]
[Horse Guide.odt](https://github.com/Wildlander-mod/Support/files/11154309/Horse.Guide.odt)

**Comment by JustPlainOldCrispy** [comment]
Submitting this to hopefully be helpful to people who, like me, appreciate and actively support having an entire herd of horses, one for yourself and each of your followers.  It's not as easy as it seems!

**Comment by Mieekaserra** [comment]
Added this to the existing (extremely minimal) horse guide.
https://wiki.wildlandermod.com/04WildlanderWorld/13-%20Horses/
