### ISSUE TITLE
[CG]

### ISSUE THREAD

**Issue by Biitap** [Wildlander-mod/Support#24]
## Submitted By
Netorabbit. 

## Description

 2-Handed Evasion based character with investment into quality-of-life skills (*The Optimized/Milkdrinker Barbarian*). Metagaming-based, rp-unfriendly build. Made with optimizations learned from my barbarian playthrough that taught me how to play Wildlander. 
[Google Doc.](https://docs.google.com/document/d/e/2PACX-1vSmAbcF3Gol3N4d20NBXkMIZIORh2uOE0Kk8zl9ctMzrBtBtbz-cDuTnzMkH_73g1vt3SU18Z_8389R/pub) 
*The guide is wordy and goes into nearly every facet of the build. Reading on the google doc is recommended.* 

Race | Stone | Blessing | Supernatural
|--|--|--|--|
Breton/Imperial/Nord/Orc | Steed, then Lord, Warrior on Aetherium Crown | Arkay, then Akatosh post-alduin  | Werewolf / Dragonborn

### Main Skills

- **Evasion:** Grab Every Perk except for Dodge.

- **Two-Handed:** Grab Every perk. Pick your favorite focuses.

### Secondary Skills

- **Restoration:** Novice Restoration, Improved Healing, Respite, Mysticism.

- **Alteration:** Novice Alteration, Apprentice Alteration, Magic Resistance (3/3).

- **Blocking:** Improved Blocking, Experienced Blocking.

- **Enchanting:** Enchanter’s Insight (1/2), Soul Gem Mastery, Arcane Experimentation, Artificer's Insight.

- **Alchemy:** The skills you are aiming for are Fortified Muscles, Regenerator and Alchemical Intellect.

### Tertiary Skills

- **Smithing:** Craftsmanship, Advanced Blacksmithing, Legendary Blacksmithing, Dwarven, Orcish, Ebony, Daedric and/or Dragon.

- **Lockpicking**: Cheap Tricks, Locksmithing Lore, Masterly Lore.

- **Conjuration:** No Perks. Level 90.

- **Destruction:** Frost/Lightning/Fire Mastery. *(x)mancy (1/2).

- **Speech:** Lore of the Thu’um, Indomitable Force, Destructive Urge, Spiritual Equilibrium . Level 100.

- **Illusion:** Expert Illusion, Shadow Shaping.

## Skill Analysis

- **Two-Handed:** Every perk in this tree has DPS and/or Burst damage increasing properties. Level 75 can be considered an end-game stage.

- **Evasion:** Similar to the two handed tree, except this tree also includes tons of stamina management bonuses along with movement speed increases. The level 100 perk in particular practically enables you to facetank. Level 75 can be considered an end-game enabler.

- **Blocking:** You practically do not need to invest any perks into this tree. Blocking is a busted skill especially if you have high amounts of HP. I recommend only investing into the two perks listed.

- **Restoration:** It’s mostly to give yourself healing aura utility. Mysticism makes Sun-based spells more powerful, and they become a good option for fighting undead both early and late-game. Sunburst in particular can 2-3 shot dragon priests from a safe distance.

- **Alteration:** This tree is taken purely for Greater Magic Resistance. However, you gain access to utility spells like Featherfalling, Transmute Muscles, Magelight, Knock, and being able to wear Mage Armor on top of your Evasion Gear. You can invest further into Spell Armor, Magical Absorption and Metamagical Empowerment if you wish to use clothing instead of armor. The perks used are minimal, but you can definitely safely invest more into this tree without regrets.

- **Illusion:** This tree is mainly for blur. To use Blur you need zero perk investment into this tree. However, Shadowshield can be a neat dps increasing tool while also providing extra defense. Feel free to only use Blur and invest nothing into the tree, though.

- **Destruction:** This tree performs two jobs: Necro Amulet cheese and extra elemental defense. It would go against the spirit of the build to rely on this tree for anything other than pesky dragons that refuse to land, so with that in mind, use only apprentice level spells for ranged damage support. Otherwise, don’t invest anything into this tree. It’s mainly to pair up with Archmage Boots for decent elemental resistance while saving space for utility enchants on your gear.

- **Conjuration:** Purely for acquiring sigil stone from the level 90 mastery quest so you can craft Daedra hearts at the Atronach forge. Can safely be ignored otherwise. Do not invest into this tree at all.

- **Speech:** This is only for the shout related perks. You do not need to invest anything into this tree otherwise. Getting gold is easy and reaching level 100 means you’ll pass every speech check anyways. If you feel like you don’t need the shout perks, you can safely ignore this tree. It will level up as you buy-sell and interact with NPCs. so it’s a good way of earning extra perk points.

- **Lockpicking:** Small utility in being able to open up chests for cheap. Also, leveling it to a 100 will grant you extra perks points to play with.

- **Enchanting:** This tree is only for acquiring Artificer's Insight, giving you access to the Spellbreaking and Annihilation enchants so that you can then put them on your weapons using Sergius Turianus or Neloth’s enchanting services. Spellbreaking in particular is really useful if you wish to go melee-only against priests and invaluable on the Miraak fight. You can also grab the rest of the perks of this tree for the sake of convenience so you can enchant items on your own.

- **Smithing:** If you’re not planning to use Daedric battlestaves, don’t bother. Use Eorlund’s services after finishing the companion’s questline (it’s easy) to order and maintain dragon weapons. Perhaps you could find a way to get Eorlund to craft Daedric stuff for you if you somehow get him on his forge in the middle of the night, otherwise you’ll have to invest heavily into the tree to do it yourself. Stalhrim perk is recommended if you’re going all into enchanting, as it undoes the Bend the Law of Firsts 25% de-buff on pieces of Stalhrim you’ve crafted yourself, letting you put two max-power enchants on a single piece of gear instead of them being at 75% power.

- **Alchemy:** Absolutely broken tree when fully invested into. I use this tree to get the three perks outlined above, but you can make yourself a millionaire several times over with this tree to pay for training for all classes, on top of being able to make nasty 40-100/second hp/magicka/stamina recovery potions with the help of Spell Research.

## Builds

[Quality-of-Life](https://www.google.com/url?q=https://banananaut.github.io/NannerPlanner/?p%3D0%26b%3DAgAAAAA8JQoMZGRkBWRkZAoFBQUKBWRkBWRkIAQEAe72A4wAAADd2A_9_AAAAAAAAAAACAPo-AAHnAHw&sa=D&source=editors&ust=1682190203129972&usg=AOvVaw0KOco81WzLBxlpUbM7ReZp)

[Basic](https://www.google.com/url?q=https://banananaut.github.io/NannerPlanner/?p%3D1%26b%3DAgEAAAEhEQYJChkFFAVLZAUKBQUFBUsFBQpkAAEEAQAGAggAAAAAAAuF_AAAAAAAAAAACAMAAAAFFAHw&sa=D&source=editors&ust=1682190203130432&usg=AOvVaw01u8qpjggXy9lXxcj8n9rU)

[Maxed Out](https://www.google.com/url?q=https://banananaut.github.io/NannerPlanner/?p%3D0%26b%3DAgAAAABCKgYRZGRkWmRkZAVkBQUFBWRkBWRkIAEEAe7_s_wAAADd2AuF_AAAAAAAAAAACANo-AAHnG_w&sa=D&source=editors&ust=1682190203130858&usg=AOvVaw2Y8Le8B6-W_rKE5_nYqPCR)

## Level ups

150 Base Magicka. Start investing early if you feel confident in avoiding damage and managing stamina.

*player.getavinfo magicka* in the console (no parentheses). Computed base.

Aside from that, feel free to level up your hp:stamina in a 3:1 ratio.  

The planner shows more of a 1:2 ratio, but you can totally go with lower stamina, especially if you're not a Nord.

### Early Game

**Weapons:**
- Swords for soft targets, Battlestaff for Hard targets.  

- You will be aiming to acquire a Silver Greatsword early game. (Companions Guild questline)

**Armor:**
- Literally anything that you can wear.  

- Piss off Thalmor if you're brave enough for their gear. Their boots, chest and helmets tend to have decent enchants..

- With high enough speech, you can kill Vex in the Ragged Flagon by taunting her. This will not net a murder and the Thieves' Guild will not become hostile. You will lose access to the Thieves' Guild questline. You'll get a kickass early game set.

- Help Grelka for a nice chest piece if you don’t feel confident in killing Vex.

**Rings/Amulets:**
- Fortify Two-handed, Elemental Protection.

### Mid Game

**Weapons:**
- Rueful Axe, Stormfang, Rueful Axe (Replica) of Fire, Silver Greatsword of Fire (45 points minimum), Volendrung

- You can craft or order replicas of weapons to be made. Rueful Axe is a base powerful silver weapon. You do the math.

- Stormfang is for those pesky Enchanted Spheres. Block -> Swing -> Block -> Swing. Have a companion or Storm and Flame Atronach scrolls/staff with you at all times.

**Armor:**
- The Main piece of gear you want is the coveted Savior's Hide. 100% Poison resistance, High magic resistance. You need to be strong enough to kill a werewolf. So be ready.

- Everything else is exactly the same as the early game: Just get whatever utility gear you can.

- Peerless fortify two-handed, elemental resistance, etc.

**Clothing:**
- Enchant 3 different cloaks/coats/capes, one with Fire resistance, one with Frost, one with Storm. Gain access to Neloth in solstheim or Sergius in the college. (protip: they'll also enchant those artifact weapon replicas)

- Expert/Master Mage Boots 

**Rings/Amulets:**
- Ring of Namira. Trivial to acquire with 50% Magic resistance and 50% Frost resistance.

- Necromancer Amulet.  150 Base Magicka Required.  

- Gauldur Amulet. Workhorse Amulet. Need level 25 in a school of magic and be able to cast a spell in said school to access. By now you should already have level 75 alteration.

### Late Game

**Weapons:**
- Bloodskal Blade if it hasn't bugged. Replica of Fire if it has. Or Rueful Axe Replica. (Undead Killing)

- Daedric/Dragonbone/Stalhrim Greatsword of Annihilation OR Daedric Battlestaff of Annihilation (enchanting level 75, max it out to a 100 please)

- Dragonbone/Daedric/Stalhrim Greatsword of Spellbreaking (for Disabling dragon priests, Miraak included) OR Daedric Battlestaff of Spellbreaking (enchanting level 75, max it out to a 100 please)

- You get one free Daedric Battlestaff from killing Ochendor, but you need to spend 1 extra perk point to increase its potency.  

- Stormfang or your own Dragonbone/Stalhrim/Daedric Greatsword of Shock II or Daedric Battlestaff of Shock II

- Daedric Gear is for dealing with Slighted, Dremora, and dispatching Atronachs quickly.  

**Gear:**
- Savior's Hide

- Archmage Boots

- Konahrik

- Aetherial Crown (Warrior Stone)

- Peerless Two-handed Gauntlets

- Peerless Two-handed Ring

- Ring of Namira

- Necromancer Amulet

- Gauldur Amulet

- 49% Elemental Resistance Cloaks

## Recommendations

Join the Companions. 

Spend the early game leveling your combat skills to around 40-50 without worrying about tradeskills. Try to dabble into trade skills and buying/selling so that your smithing, alchemy, enchanting and speech don’t fall too far behind. Once you’re tired of bandits, work on getting Your trade skills to a 100 and your Alteration to 75.

Complete the Mehrunes Dagon quest to gain access to two Daedra hearts after killing two dremoras (go into it with high confidence and skill level). You need one for Alchemical Intellect. Subsequent hearts can be acquired by completing difficult content and in black book lootable inventories. I found 8 hearts total in my playthrough. 90 Conjuration will grant you access to a sigil stone, which you can use to craft more hearts. But it’s a steep time investment for something that you honestly do not need. Alternatively, you can kill all of Boethiah’s followers to anger him and fight 6 dremora that can respawn if you spend enough time away from the cell.

Ebony Vampires are weak to silver, but they’re far weaker to getting whacked by a Daedric Battlestaff or Warhammer. Try experimenting with a Silver Battlestaff of Fire.

Do not bother using blunt weapons to hunt down dragon priests. Use silver Greatswords of Fire, or Bloodskal Blade/Replica of Fire. Rueful Axe/Replica of Fire is also OK. You normally have to be able to defeat a dragon priest to freely use the Bloodskal Blade, but you can use two scrolls of Mark & Recall to obtain it and leave. Place a mark elsewhere outside the barrow, and then use another scroll to leave once you’ve obtained the sword. The sword’s power attack can be used to interrupt Duukan and stop him from using his lightning cloak but this isn’t a 100% guarantee. Very consistent, though. If you have Spellbreaking, it’s much easier. The issue with the DPs is less their HP regen and more that it’s paired up with a cloak that doesn’t care about how much magic/elemental resistance you have.

Generally you want to aim for 60 elemental defense and 60 magic defense. Having more generally felt pointless during the run. 90/90 (the cap) does nothing to aid against dragon priests and mistmen.

I recommend being able to defeat Duukan before taking on the soul cairn in the dawnguard questline. Having access to yol’s augment (fire wraiths) turns the soul cairn from the most awfully balanced and over-tuned content in the game to a walk in the park. We’re talking about 1 hour of clear time with Yol vs potentially 5-7 hours without it plus all the pots you’ll be using up trying to survive the wrath of the mistmen combined with Slighted.

You’ll want to be using a companion. At least one companion or Atronach with you CAN make the difference early on. Late-game though, they stop being of use and they become a distraction at best and a babysitting job at worst.

You can reach a comfortable 49/55 Elemental/Magic resistance without investing into destruction and minimal investment into alteration if you sacrifice damage. It won’t be too bad.

- Lord Stone(15), Magic Res 1 (10), Agent of Mara(5), Saviour’s Hide (25)

- Cloak, Boots, Rings with 49%.

You get to keep your neck slot and your head slot free to equip anything you wish. (gauldur, kohnariik, etc.)

You can check Alchemists whenever you visit a town for magic res pots (good), they last 5 minutes and are worth having around.

Kill every dragon you come across and get their blood. Endgame amount (for Alduin, Miraak, Ebony Warrior) should be around 15 dragons slain for you to divide up into slow time and attack speed pots.  The more the merrier + you'll be unlocking more shouts, increasing your cooldown reduction.

You don’t get to kill Karstaag. So just forget about it. I don’t even know where to find him, so don’t ask. If you’ve used a similar build to defeat him let me know and I will add the process to the google doc. 

## Additional Information
Special thanks to Special thanks to HiHat_2436 for further optimizations and discussion.
Special thanks to Lizzy for the floggings and technical things my feeble mind can't comprehend. 

**You may NOT contact or pester Lizzy and HiHat_2436 for anything related to this guide, this includes suggestions, comments, critiques, words of encouragement, etc. This is not an exhaustive list.**

**Comment by Mieekaserra** [comment]
https://wiki.wildlandermod.com/15ClassGuides/MilkdrinkerBarbarian/
