### ISSUE TITLE
Images under spoiler tag not appearing.

### ISSUE THREAD

**Issue by Nathan-Shea** [Wildlander-mod/Support#25]
**Which page**
https://github.com/Wildlander-mod/wildlander-mod.github.io/blob/69c55dde5a070693628b7acfbd460eca852d2028/_05-HintsandTips/The-Milk-Drinkers-Guide-to-Power-Leveling.md?plain=1#L52

**Description of issue**
The three images under the spoiler tag are not showing. Works fine when previewing the code but not on the published website. This issue is appearing in both FF and Chromium.

**Screenshot to help me find it**
![Screenshot 2023-06-08 183940](https://github.com/Wildlander-mod/Support/assets/88519724/348b0a5c-d71a-40da-89f5-a316c6245835)

**Comment by Nathan-Shea** [comment]
Could be a Jekyll problem? 
https://github.com/Wildlander-mod/wildlander-mod.github.io/blob/69c55dde5a070693628b7acfbd460eca852d2028/README.md?plain=1#L8

**Comment by Mieekaserra** [comment]
Issue corrected.
