### ISSUE TITLE
Table issues in followers.

### ISSUE THREAD

**Issue by Nathan-Shea** [Wildlander-mod/Support#26]
**Which page**

https://github.com/Wildlander-mod/wildlander-mod.github.io/blob/c8e708d7ff90b43c574f9c28b71747990a6c3c7b/_04WildlanderWorld/7-Available-Followers.md

**Description of issue**
Tables missing because of formatting issues.

**Screenshot to help me find it**
![image](https://github.com/Wildlander-mod/Support/assets/88519724/cdf49a12-c4d9-45fb-95e8-a20157257eee)

I created a pull request on the page fixing this. I tested it on my computer and it works fine. Apologies if I have broken Github etiquette by creating a pull request and no issue I'm new to this stuff.

**Comment by Mieekaserra** [comment]
Merged.
