### ISSUE TITLE
Class Guide - Scout

### ISSUE THREAD

**Issue by Friederichh** [Wildlander-mod/Support#29]
## Description

The scout class was a classic option in both Morrowind and Oblivion. Wildlander's default classes include a version of this class, as does Noxcrab's list of Requiem classes. The version in this guide adds a couple of important twists. The Wildlander default scout class leans into the idea of an independent ranger of the wilds by including both Alchemy and Smithing. Noxcrab's take focuses on skirmishing from range. This version utilizes Redguard Adrenaline Rush and boosts to one handed to focus more on fast paced, open melee combat while taking advantage of Honed Metal to replace Smithing with Alteration, ultimately providing the additional protection needed for a more combat focused playstyle.

Adrenaline rush, poison resistance, and stamina costs make Redguard a very appealing race for this class. Orcs and Khajiit could both work as well focusing on offense, or Nord for a more defensive style. The Warrior stone's damage bonuses are by far the best for the combat focus and allow for taking on pretty strong enemies pretty quickly. The Julianos blessing can be a helpful way to power alteration for this build, although Talos and Boethiah both better fit the emphasis on combat depending on roleplay. Naturally, this build is compatible with a number of different roleplays.

I have a video playlist demonstrating my take on the class through the first ebony vampire and dragon [here](https://www.youtube.com/playlist?list=PLX80A-ybioQehyobYhr-pEQHFbBQqHLQB).

Race | Stone | Blessing | Supernatural
|--|--|--|--|
Redguard | Warrior Stone | Julianos (or Talos/Boethiah) | (optional) Werewolf

### Starting Skills
One-handed / Evasion / Block / Marksman / Alteration / Alchemy

One-handed will be far and away the main source of damage, focusing on war axes to get the most out of the skill. One-handed and evasion at 75, block at 50 unlocks generic late game enemies like dragons, dragonpriests, slighted, ebony vampires, etc. Alteration at 75 for 3 ranks of magic resistance + Shield of Solitude is more than enough for endgame.

### Secondary Skills

Sneak / Speechcraft (optional)

Sneak is a quality of life skill for preparing for combat and strong openings on certain encounters.

## Perks

See my discussion [here](https://youtu.be/DD3IKkGJB_k?si=CV7aRr1HMwK5dcL7)

## Level ups

I generally go 4:1 health:stamina. You can change this to your preference.

## Recommended weapons / Spells

War-axes perform the best, but you can change to sword or mace for RP reasons.

Generally any war-axe -> Dawnguard or Skyforge Steel War-axe -> Dawnguard rune axe or Ebony war-axe or Daedric war-axe

For marksmanship, use your crossbow of choice.

Mage Armor, Transmute Muscles, and Knock spells from alteration.

Poisons of paralysis can come in clutch.

## Recommended armor / Clothing

I go for hand-placed drops, chest loot, and merchant buys as follows:

Head: Any -> Circlet of peerless archery or alteration
Chest: Any -> Scaled Cuirass of the Traveler -> Glass cuirass of extreme health
Gloves: Any -> Glass gauntlets of Extreme Wielding
Boots: Any -> Elven or glass enchanted for fire or frost resist
Neck: Gauldur Amulet*
Ring: Kematu's Ring of Eminent Wielding -> Ring of peerless wielding
Cloak: Enchant for frost resist
Shield: Shield of Solitude*

*technically from quests

Savior's Hide magic resist if overkill on this build. Other good options include the Deathbrand armor set or Chitin Morag Tong Elite armor set if you want to do Solstheim. 

## Content 

Companions for Eorlund's smithing services and at least starting the college for Saarthal and Sergius' enchanting services is a must.
Man Who Cried Wolf -> Wolf Queen Awakened (for Shield of Solitude)
In My Time of Need (Kematu's Ring of Eminent Wielding), Missing in Action (Glass Cuirass of Extreme Health), Forbidden Legend (Gauldur Amulet)

## Additional Information

Training, especially for One-handed, evasion, and alteration keeps the playthrough fast and fun.
I think followers are fun with this build as long as they're at least as sneaky as you are and not too tanky (e.g., Jenassa, Aela, etc.)

**Comment by Mieekaserra** [comment]
Added to wiki. please give 10 mins to deploy.
