### ISSUE TITLE
Wiki - How-Do-i/EditUi - Add Frostfall-Meters Info

### ISSUE THREAD

**Issue by MilesTeg81** [Wildlander-mod/Support#30]
**Page which needs this content adding**
https://wiki.wildlandermod.com/09-How-Do-i/EditUi/

**Whats missing?**
The Temperature-Meters

**Suggestion for Text**
"Disclaimer about Frostfall-Profiles: First switch the Frostfall profile (otherwise you'll overwrite Wildlander-defaults ("ULTSKY010-WORKING" and can't easily switch back): Under "Profiles" select another one (#2 to #10). See MCM "About Settings Profile" for details. And NEVER use "DEFAULT CURRENT PROFILE!"

"Navigate to the "Frostfall" MCM, select “Meters”. You can change the Display Mode from always-on to contextual. Under "Advanced settings" you can customize position, scale, color and opacity."

**Comment by Mieekaserra** [comment]
Added changes to include frostfall meter configuration
