### ISSUE TITLE
Game is not playing

### ISSUE THREAD

**Issue by solohex** [Wildlander-mod/Support#7]
Hi there I got this mod pack a couple days ago, I recently got to installing all the mods for it, I have the launcher up I have left it up for most of the day today but it is not playing, any time I press the launch button it says that skyrim is loading/playing this process will take up to several minutes and that this is not an error any advice will be greatly appreciated hope you have a good day

**Comment by Mieekaserra** [comment]
You havent installed the pre-requirements from the install guide.
