### ISSUE TITLE
Alchemy Wiki Page Typo

### ISSUE THREAD

**Issue by JartanFTW** [Wildlander-mod/Support#8]
**Which page**
https://github.com/Wildlander-mod/Support/wiki/Alchemy
**Description of issue**
Typo ingidients > ingredients
**Screenshot to help me find it**
![image](https://user-images.githubusercontent.com/66337180/168315525-9a3fa77e-af55-4fb7-bf14-6b826dfaf8cc.png)

**Comment by Mieekaserra** [comment]
Its actually like that ingame too lol!

**Comment by Mieekaserra** [comment]
fixed
