### ISSUE TITLE
Spell additions to relevant perk pages.

### ISSUE THREAD

**Issue by 3DJutsu** [Wildlander-mod/Support#9]
**Page which needs this content adding**
https://github.com/Wildlander-mod/Support/wiki/Alteration
https://github.com/Wildlander-mod/Support/wiki/Conjuration
https://github.com/Wildlander-mod/Support/wiki/Destruction
https://github.com/Wildlander-mod/Support/wiki/Illusion
https://github.com/Wildlander-mod/Support/wiki/Restoration

**Whats missing?**
Alteration spells Mage Coat (Rank I, II, & III), and Transmute Wood
-> Renamed from Foxskin, Wolfskin, & Bearskin

Conjuration spells Bound Cloak (Rank I, & II), and Conjure Shelter (Rank I, & II)
-> Renamed from Bound Cloak Lesser/Greater, & Conjure Shelter Lesser/Greater

Destruction spell Vapor Blast

Illusion spells Soothe (Rank I, II, & III)
-> Renamed from Soothe, Bask, & Revel

Restoration spell Kindle

EDIT: Also the Conjuration spells "Bound Hunting Knife", and "Summon Gargoyle/Gargoyle Brute/Gargoyle Sentinel" (apparently learned only from Spell Research)
"Summon Invisible Stalker" no longer seems to be in the game.

EDIT 2: Dragonborn DLC Spells aren't on the list either.
     Alteration: Ash Rune, Ash Shell
     Conjuration: Bound Dagger, Conjure Ash Guardian, Conjure Ash Spawn, Conjure Seeker (from what I understand it's a very powerful summon and is oddly costed for it's level, why not reclass it to Master tier?)
     Destruction: Whirlwind Cloak, Poison Rune (reclassed from Resto to Destruction in Requiem); Ignite and Freeze *may* apply, but they're only gained while wearing a specific ring
     Illusion: Frenzy Rune (The Tome for which teaches "Frenzy Sphere")
     Restoration: Poison Rune (reclassed from Resto to Destruction in Requiem)

EDIT 3: Yeesh, the longer I look the more spells I find. XD 
     Alteration: Thermal Glimpse, Thermal Vision
     Conjuration: Necromantic Empowerment on Target and Self
     Illusion: Night Glimpse, Night Vision

**Link to page addition**
Please provide a link to a publicly available google document/sheet or equivalent which contains the content you would like adding.

Frostfall Spells
http://skyrimsurvival.com/home/frostfall/spells/

Bound Hunting Knife
https://www.nexusmods.com/skyrim/mods/59388

**Comment by Mieekaserra** [comment]
Added tables provided
